name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Prepare deployment directory containing public/index.html and src/
      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp public/index.html deploy/index.html
          cp -R src deploy/src

      # Configure GitHub Pages
      - uses: actions/configure-pages@v3

      # Upload the deploy folder as Pages artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: deploy

      # Deploy to GitHub Pages
      - uses: actions/deploy-pages@v1
