name: Deploy to GitHub Pages

# Required permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository using latest v41
      - uses: actions/checkout@v4

      # Prepare deployment directory
      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp public/index.html deploy/index.html
          cp -R src deploy/src

            # Enable Pages via API (idempotent)
      - name: Enable GitHub Pages via API
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"source":{"branch":"main","path":"/"}}'

      # Configure GitHub Pages
      - uses: actions/configure-pages@v3

      # Upload the deploy folder as Pages artifact (v2)
      - uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      # Deploy to GitHub Pages
      - uses: actions/deploy-pages@v1
