# File: .github/workflows/pages.yml
name: Deploy to GitHub Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir deploy
          cp public/index.html deploy/index.html
          cp -R src deploy/src

      - uses: actions/configure-pages@v3
        with:
          enablement: workflow

      - uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      - uses: actions/deploy-pages@v1
