name: Deploy to GitHub Pages

# Потрібні дозволи для GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Забираємо код
      - uses: actions/checkout@v4

      # 2) Готуємо папку для деплою (копіюємо index.html та весь src/)
      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir deploy
          cp index.html deploy/index.html
          cp -R src deploy/src

      # 3) Увімкнення GitHub Pages вручну через API (якщо треба)
      - name: Enable GitHub Pages via API
        env:
          PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }} # ваш PAT із правом repo
        run: |
          curl -X PUT \
            -H "Authorization: Bearer $PAGES_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pages \
            -d '{"source":{"branch":"main","path":"/"}}'

      # 4) Налаштовуємо Pages (enablement через Actions)
      - uses: actions/configure-pages@v3
        with:
          enablement: workflow

      # 5) Завантажуємо артефакт (папку deploy)
      - uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      # 6) Розгортаємо на GitHub Pages
      - uses: actions/deploy-pages@v1
